### ISSUE TITLE
Quiver...

### ISSUE THREAD

**Issue by Svarten** [arkayenro/arkinventory-classic#2] opened 2019-08-27 02:24 UTC
ArkInventory does not seem to like quivers when equiped in a bag slot :)

**Comment by arkayenro** [comment] 2019-08-27 03:28
i'll create a hunter and see if i can work out what the issue is

**Comment by arkayenro** [comment] 2019-08-27 03:52
ive got arrows working, not sure if bullets are different, will need to level up a bit to see if bullets will go into an arrow quiver or not, if not then i need to setup "quivers" for bullets as well

**Comment by arkayenro** [comment] 2019-08-27 09:39
should be fixed in 1.0.4 but probably needs more work

**Comment by Svarten** [comment] 2019-08-27 09:41
My thanks, the warning spam in chat was annoying as hell, I love ArkInventory though so... :)

**Closed** 2019-08-27 12:44 UTC
Labels: bug, enhancement
